### ISSUE TITLE
Mysql errors on product page

### ISSUE THREAD

**Issue by Chillifish** [wp-e-commerce/WP-e-Commerce#1704]
I'm getting the following when viewing a product:

WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5]
SELECT wp_posts.*, wp_term_taxonomy.term_id, wp_term_relationships.term_order FROM wp_posts INNER JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) INNER JOIN wp_term_taxonomy ON (wp_term_relationships.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id) INNER JOIN wp_postmeta ON (wp_posts.ID = wp_postmeta.post_id) WHERE 1=1 AND wp_term_taxonomy.taxonomy = 'wpsc_product_category' AND wp_term_taxonomy.term_id IN ('7') AND wp_posts.post_status IN ('publish') GROUP BY wp_posts.ID ORDER BY wp_term_taxonomy.term_id,

**Comment by JustinSainton** [comment]
Cannot replicate any more, will close for now.  If we get more reports of this with repeatable behavior, we'll see if we can fix it.

**Comment by NZSmartie** [comment]
I've come across the issue myself. using Wordpress 4.2.2, WP eCommerce 3.9.4

I'm not familiar with WP eCommerce, but after looking at  stack trace, the issue arises when `wpsc_product_sort_order_query_vars(null)` is called inside `/wpsc-components/theme-engine-v1/helpers/query.php:233`
in my case, inside `wpsc_product_sort_order_query_vars()`, `get_option('wpsc_sort_by')` returns false. Which happens when there is no entry in wp_options table. So false gets passed back into the 'orderby' filter for the query which gets processed by Wordpress. 

Not sure what the default value of 'wpsc_sort_by' should be yet. but I thought this information could be helpful

**Comment by NZSmartie** [comment]
Easiest fix is to go to the Wordpress dashboard, `Settings` -> `Store` -> `Presentation`, choose something for `Sort Product By` and then `Save Changes`
