### ISSUE TITLE
Coupon Field doesn't show on t.e. 2.0

### ISSUE THREAD

**Issue by omarabid** [wp-e-commerce/WP-e-Commerce#1737]
Coupon Field doesn't show up when you have Theme Engine 2.0 enabled. It shows fine on 1.0, though.

**Comment by JustinSainton** [comment]
After 7cd929e531fd1911ea66d3868d45bf67d41dc623, I started getting fatal errors, because somehow, it was adding the subtotal as a value in the cart_items array.  Bizarre, and not sure why, but after clearing everything out, it seems fine again.  Leaving this note here for posterity, just in case it crops up again.
