### ISSUE TITLE
Personalize Your Product - Can Not Change Default Message  "Complete this form to include a personalized message with your purchase."

### ISSUE THREAD

**Issue by bidonme** [wp-e-commerce/WP-e-Commerce#1773]
Ok, I moved the wpsc-single_product.php to my current theme. Opened the file in Appearance/Editor and modified the file. I changed as per below...

<legend><?php _e( 'Personalize Your Product', 'wpsc' ); ?></legend>
									<p><?php _e( 'Below please enter your full name or initials as per your selection to monogram below!', 'wpsc' ); ?></p>

I saved the file and when I go to the front end and view a products it still shows "Complete this form to include a personalized message with your purchase."

What am I missing?

**Comment by JeffPyeBrook** [comment]
This request belongs over in the WordPress Support forms, you should repost the message there instead of this developer site.

But the answer is...

Clear the WP-eCommerce theme cache from the store settings page
Clear the WordPress page cache
Clear any other cache like WP-SuperCache, W3TotalCache, etc

Refresh your browser cache, all should be well

**Comment by bidonme** [comment]
Thank You
