### ISSUE TITLE
Create default value for SKU

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#1799]
SKU is somewhat prominent within the back end.  In the absence of a administrator set SKU lets default the SKU to the product ID sos that there is a unique reference back to the product purchased.  This should be more useful that displaying "N/A" in all of the the places SKU is referenced.

**Comment by benhuson** [comment]
I don't think this is a good idea.

Product ID and SKU should not be considered te same or interchangeable.

If a business correctly uses SKU codes for all it's products it is probably preferable to easily identify products that do not have a SKU code, rather than showing a numeric identifier if not set.

What if a business did use SKU codes and their product Codes were or 5 characters numeric references? This would cause extreme confusion if some SKUs were set and some not but showed ID instead.

If there is a concern about prominently displaying SKU for people who don't use SKU, maybe there should just be a way to disable/hide SKU. My preference would be to display SKU by default as you really should be encouraging people to assign product codes as best practice.

**Comment by JustinSainton** [comment]
Yeah, I tend to agree with @benhuson here.  SKU == stock keeping unit.  Product IDs have nothing to do with stock.  If you want to filter the N/A, that's fine, I'd merge something for that.
