### ISSUE TITLE
value not really value in TE2 using wpsc_get_add_to_cart_form_args

### ISSUE THREAD

**Issue by curtismchale** [wp-e-commerce/WP-e-Commerce#1819]
Given this code:

```php
	public function add_te2_button( $args ){

		$args['form_actions'][] = array(
			'type' => 'submit',
			'name' => 'sfn-wish',
			'value' => 'Add to Wishlist',
			'title' => 'Add to wish',
			'class' => 'sfn-wishlist-add',
		);

		return $args;
	}
	add_filter( 'wpsc_get_add_to_cart_form_args', array( $this, 'add_te2_button' ) );
```

I would expect that the `value` would be the button value for a submit button, but it's not. The 'value' is actually the title for the button.

I'd love to know why the value !== value and change it to so that value === value

**Comment by JustinSainton** [comment]
Interesting.  So yeah, thais is annoying.  It uses `title` for the value, instead of `value`.  It swaps the attributes at the `wpsc_form_submit()` abstraction, not any lower, which is nice.

`wpsc_form_submit()` is only ever invoked in `_wpsc_filter_control_submit()`.  `_wpsc_filter_control_submit()` is only invoked via the `wpsc_control_submit` and `wpsc_action_field_submit` dynamic filters.  

Those are invoked by the Form field API abstraction, dynamically, based on the type passed.  This is good news - it means we can simply find any core area that the 'submit' type is set, change 'title' to 'value', and swap it out at `wpsc_form_submit()`.

**Comment by JustinSainton** [comment]
Cool, should be sorted out now.  Handled at the `_wpsc_filter_control_submit()` layer primarily, so as not to adjust a paradigm that is really implemented throughout the rest of the API. 

Basically, you can use title and value interchangably on the submit type now.
