### ISSUE TITLE
Disable shipping for fresh installs

### ISSUE THREAD

**Issue by misulicus** [wp-e-commerce/WP-e-Commerce#1978]
Just installed master fresh and shipping was enabled even tho i had no shipping gateways
I think it should be OFF by default

**Comment by JustinSainton** [comment]
Would love some discussion + thought on this from other committers:

@wp-e-commerce/core-team

**Comment by benhuson** [comment]
Shipping tends to be one of those things that people don't always think about until the last minute when setting up an online store. In my experience, when raising the question of shipping, it's not always something people have put a lot of thought into even though it's obviously a crucial part of selling online (unless just selling downloads).

In my opinion, shipping is something we should not default to pre-configuring in any way so that the store owner is obliged to think about what type of shipping setup they need.

As @misulicus says, it feels odd having shipping on by default if no shipping methods are selected. However we should have a shipping method active by default which leads me to think that default to off might be best.
