### ISSUE TITLE
No cart info on checkout page - Theme engine v2 feedback

### ISSUE THREAD

**Issue by leewillis77** [wp-e-commerce/WP-e-Commerce#2299]
I've been testing http://wordpress.org/plugins/cart-recovery/ against branch-4.0.0. 

Currently the plugin generates an abandoned cart email that links the user back to the checkout page with their basket populated. 

On the old system, this page includes the cart summary at the top of the page:
https://www.dropbox.com/s/qibxe08afbf1d83/Screenshot%202017-03-13%2017.33.44.png?dl=0

On the new system, there's nothing on the checkout page to say what's being purchased:
https://www.dropbox.com/s/niwergt4wz14ucj/Screenshot%202017-03-13%2017.36.27.png?dl=0

Is that a deliberate choice? If so - I'll probably update my plugin to bring people back to the cart page, rather than checkout if they're running TEv2

**Comment by JustinSainton** [comment]
@leewillis77 Good question! It's been this way since very early in the development of this theme engine, so I'm not aware of how deliberately that was done. It was developed against Baymard Institute's usability guidelines for eCommerce.  At the time, Baymard concluded that the most usable cart in their testing was Crate & Barrel's - which is still fantastic.  They (and many others, to be sure) separate the "cart" from the checkout process.  I'm not sure how much of a role that all played in this decision, but that likely contributed.

I imagine we'll likely keep it as-is, and it would probably be worth bringing people to the cart page if they are using the 2.0 theme engine.  You can check that via `wpsc_is_theme_engine( '2.0' )` or something like that.

Thanks for the report, @leewillis77!

**Comment by leewillis77** [comment]
Ack - thanks for the detailed response Justin!
