### ISSUE TITLE
If wpsc-user-log.php is already in active theme, new actions (which are required), are not utilized.

### ISSUE THREAD

**Issue by JustinSainton** [wp-e-commerce/WP-e-Commerce#359]
This is a problem.  If the user has already moved wpsc-user-log.php to their active theme, the new  'wpsc_user_profile_section_' . $current_tab action is not utilized.  This means that a large, large portion of users won't be able to access Customer Details or Downloads (or, very likely, other tabs plugins may have added).

We need to figure out how to maintain back compat here.

**Comment by Poikilos** [comment]
If anyone comes to this issue looking for more info about manual steps that may be needed (the warning message's solution link is broken, but the first link goes to this issue), the manual changes to wpsc-user-log.php may not be needed anymore with later versions according to comments at (people say to click "ignore" on the message or that later version "finally works": <https://wpecommerce.org/wp-e-commerce-plugin/wpec-3-8-11-1-weve-fixed-your-stuff/>.
Here is the error that may lead people here:
<details>
<summary>(click to show error)</summary>

> You are currently using WPeC 3.13.1. We introduced a regression in WPeC 3.8.10 which affects your customer user account page. We have included a fix for a [bug on the User Account management page](https://github.com/wp-e-commerce/WP-e-Commerce/issues/359). We are able to fix this automatically on most sites, but it appears that you have made changes to your wpsc-user-log.php page. For that reason, we have some [simple instructions](http://docs.wpecommerce.org/documentation/3-8-11-user-logs) for you to follow to resolve the issue. We are sorry for the inconvenience.

</details>

I have no way to test whether this is causing a problem, since my customer only uses WP eCommerce for display purposes (for products that can be ordered in bulk), and has the cart features hidden and the prices at $0.00 and same color as background (on purpose and not related to issue).
If manual steps are still needed in the case of this error message, someone here please explain what the manual steps are since the second link above ("simple instructions") is broken. Otherwise, please confirm manual steps are not needed.
