### ISSUE TITLE
Presentation Settings

### ISSUE THREAD

**Issue by instinct** [wp-e-commerce/WP-e-Commerce#516]
Here is an over view of the old / existing presentation settings.

What do you guys think should be included in WPEC 3.9 and what do you guys think should be taken out and put into a separate Plugin?

@garyc40 and I both feel that if WordPress itself offers a comparable setting for pages or posts we should offer something similar for products. So for instance we should keep the number or products to show per page setting - whereas something like IntenseDebate should be made into a Plugin.

On the flip side there are certain e-Commerce settings that our users love that are very specific to e-Commerce that doing have any corresponding WordPress comparison i.e. product thumbnail settings. 

However I've been to WordCamps where people have praised us about our ability to customise the product grid and thumbnail image size - I like this because I might want to use a non e-Commerce themes that doesn't specify these options and I don't want to have to learn CSS in order to use WPEC with my favorite theme... 

Im playing devils advocate. Tell us what you think should stay and go into a free customizer Plugin.

I've attached an image showing what it looks like now for reference:
![wpec-presentation-settings](https://f.cloud.github.com/assets/917424/684641/53fae872-da01-11e2-8be8-26df0b93788b.png)

And here is the link to the new theme engine plugin: https://github.com/wp-e-commerce/wpec-theme-engine-v2

It got a whole lot of update love yesterday. Let us know what you think :)

**Comment by danmilward** [comment]
@benhuson just checking, I know its been a long time but do you know whether or not @garyc40 ever got around to nailing the AJAX support. If so are you still a fan of spinning out Fancy Notifications into its own Plugin?

**Comment by JustinSainton** [comment]
@danmilward AJAX support was never added. The only javascript included on the front-end of the theme engine revolves around the shipping calculator, country drop downs, and payment method selection - none of those adding any AJAX requests

**Comment by JustinSainton** [comment]
Hey guys,

I think there has been some _really_ good conversation on this thread over the years, but it's probably tie to break it down into distinct, actionable steps and put it out to pasture.  I'll propose steps in this comment and hopefully, over the next week or so, we can gain consensus among those who have weighed in.  As that occurs, we'll move each item into it's own issue, and close this issue down.

## Proposal

@DavidWestbrook made this timely (at the time) comment:
> One is that I think of the customizer as theme territory and WPEC as a plugin

What we have all seen over the course of the last couple years is that the Customizer is no longer just for themes, it is for _anything_ - but most especially, things that benefit from live previewing.  It's not just for themes. It's not even just for settings. It's for _anything_.  And even though some are kicking and screaming, it's the way of the future for WordPress. 

My proposal is simple: no new presentational settings, _anywhere_, except the Customizer.  Not as a plugin, in core.  Any non-presentational setting gets a :-1: by default.  Every setting has to justify itself and fight for it's life.  @garyc40's extremist views towards the settings that had accumulated in the old theme engine were as right on 19 months ago as they are today.

### But Wait, Where's X?
This will naturally be the next question people have.  What happened to X/Y/Z?  WHERE ARE MY FANCY NOTIFICATIONS???

This will be natural, and it will be okay.  As long as our templates have a way to add functionality to them (they do) and our settings API has the ability to add settings to specific pages (it does) - developers can fill in the gaps that we create.  But honestly - I think we'll find that maybe 80-90% of people are actually overwhelmed at the number of options, confused by what they actually do, and don't care about most of them.

### Next Steps
With all that said, here are the settings I think we should add.  I've separated presentational from non-presentational.  All presentational settings should go into the Customizer.  Non-presentational items can go into the settings tab which is labeled, ironically, Presentation.

*Presentational*
- [ ] Add to Cart Notifications (This should be a template part that themes can customize, and off by default.)
- [ ] Layout (Grid/List/etc.)
- [ ] Products Per Row (if Grid View is selected)
- [ ] Thumbnail Settings

*Non-Presentational*
- [ ] Enable AJAX (We have no AJAX functionality yet.  I'd like to see this in 4.1.  On by default)
- [ ] Enable Responsive (Theme Engine has no base responsive styles yet.  We get asked about this _all the time_.  Literally, probably daily.)
- [ ] Products Per Page (Note: I'm *not* for adding back the positioning of the pagination, or whether or not to turn it on/off.  Pagination should always be top + bottom, and should always be on.)

A quick note: I'm a bit on the fence about the settings for enqueueing/dequeueing scripts/styles. Settings for that have existed in the theme engine since its inception - so I'm _sort_ of okay with it...but it still feels like something that child themes should be handling in functions.php, or functionality plugins can handle with a very simple filter.

However - take a second.  Go, look at the settings page in the screenshot with the original comment.  Now - imagine only having 7 (4 new,+ 3 existing) settings in the settings area for Presentation.  And imagine having only 4 presentational settings in the Customizer.  _So much better_.  *Especially* being able to live preview layout changes, thumbnail sizing, etc.

Assuming we have some consensus here (Please weigh in @DavidWestbrook @benhuson @leewillis77 @JeffPyeBrook @misulicus @edoriv @instinct and anyone else with an opinion), we can go ahead and create new issues for each of those checkboxes, and plan on iterating all of this into 4.1

**Comment by danmilward** [comment]
Better if you like empty pages ;)

No, I agree that some things should be made into Plugins but I don't think we should push 4.0 out the door until we have some other options for our users. Its the right thing to do. 

Some useful text on this page would be a link to our marketplace so people can find alternatives. But stress while there are no alternatives in our marketplace we'd be committing marketing suicide without having alternatives for some of the ones we know people use.

**Comment by benhuson** [comment]
Completely agree that it would make sense not to remove anything in a release until there is an existing alternative as a plugin.

There is such a big user base that could be using presentational settings in a multitude of different configurations, many of whom may not be developers, so removing something without filling the gap would probably not be a good idea.

**Comment by danmilward** [comment]
Yes. That said I don't accept its not possible to replace a chunk of these with Plugins pretty quick.

What would you say are urgent plugins Be?

I'm pretty sure there are related products and reviews plugins. 

The smart thing to do is create a plugin or plugins that cover us for what we can deduce as the really obvious ones.

**Comment by benhuson** [comment]
I've started playing with splitting out Fancy Notifications as a component so that it could then be split off as a plugin and made compatible with the new Theme engine.

I basically added some JS events 'wpscAddToBasket' and 'wpscAddedToBasket' which are triggered when the Add to Basket button is clicked and when a successful response is returned, enabling anything (such as Fancy Notifications) so be triggered.

I'll push up something for you to see when I have tidied it up a little - probably as a separate issue.

PS. Just occurred to me, terminology-wise should we be using 'cart' or 'basket'?

**Comment by danmilward** [comment]
Hmmm I think cart is probably a more recognized / ubiquitous term. I think we should use that.

Any other thoughts?

**Comment by JustinSainton** [comment]
@benhuson @danmilward :+1: on using Cart, instead of Basket.

**Comment by JustinSainton** [comment]
Moving this back to 4.0. I think there seems to be some consensus that we need AJAX and Cart Notifications for 4.0.  So let's take our time (we're in no rush) and do it right.

**Comment by instinct** [comment]
High five! Totally agree with this.

**Comment by JustinSainton** [comment]
Also, FWIW - I'm not entirely convinced that we should go the plugin route for these things. If we're going to provide a canonical way of doing these things, it may as well be in core.  If plugins/themes want to override these things, we should make that easy.

**Comment by benhuson** [comment]
@JustinSainton I think it makes sense to keep most existing functionality within hook but make it easily unhookable. I think it makes sense to try to modularise some of this functionality though.

Here's my first stab at moving all Fancy Notification functionality into a standalone component that could be easily split out if desired:
https://github.com/benhuson/WP-e-Commerce/commits/fancy-notifications

(note, I haven;t changed the "basket"/"cart" terminology yet)

**Comment by benhuson** [comment]
Rebased version of Fancy Notification module is submitted as PR #2020

**Comment by JustinSainton** [comment]
thanks @benhuson! will review shortly

**Comment by lizkaraffa** [comment]
So i'm weighing in super late in the game, but as I'd classify myself currently more in the end user role than with my developer brain on I think we shouldn't be too hasty to push things into their own plugins.  I consider myself to be pretty internet savvy but I hate and often forget to look up a bunch of other plugins that would pair nicely with what I'm doing.  Since the world has become infinite options having more plugins for people to try and choose from is almost similar to the fancy notification debate before, going back and forth between the cart and products is in the same annoyance for needing a bunch of plugins/having settings all over the place, you might lose people on WPEC in general.  

I get the developer side of keeping things lean and separated and only providing limited options versus overload.  There is a lot of wisdom and truth to that.  At the same time, I think a lot of users want 95% of their ecommerce stuff to be handled by one ecommerce solution out of the box.  To me, if we've identified certain functionality and features as really important to our current user base, pushing that out into a separate plugin would not be taken favorably unless we have a nearly painless almost automatic onboarding process for those now separate plugins.

**Comment by JustinSainton** [comment]
@lizkaraffa I tend to agree. WordPress core hasn't solved plugin dependencies yet - and existing solutions (TGMPA) are clunky.  If we can avoid external dependencies, we should.

**Comment by lizkaraffa** [comment]
This is what will be placed in customizer per @JustinSainton  
- Add to Cart Notifications (This should be a template part that themes can customize, and off by default.)
- Layout (Grid/List/etc.)
- Products Per Row (if Grid View is selected)
- Thumbnail Settings
-  Products Per Page (Note: I'm not for adding back the positioning of the pagination, or whether or not to turn it on/off. Pagination should always be top + bottom, and should always be on.)

Also on settings page add a button to do these settings in customizer

**Comment by danmilward** [comment]
Nice work @lizkaraffa ... I've been agreeing with you re leaving what people still like about WPEC the hell alone since 2014. Nope make that 2013 ;)

**Comment by JustinSainton** [comment]
Note: to effectively implement most of the customizer changes we're wanting to implement, we'll want to integrate with the new Selective Refresh functionality. https://make.wordpress.org/core/2016/02/16/selective-refresh-in-the-customizer/

**Comment by JustinSainton** [comment]
Marking this as done! I expect we'll iterate on this, but closing the books on this now nearly 3 year old ticket feels quite nice :)

![customizer](https://cloud.githubusercontent.com/assets/1168754/15620418/ec28975c-240e-11e6-8137-a128a4035c60.gif)

**Comment by danmilward** [comment]
I'm glad we waited three years because this is awesome :)

**Comment by JustinSainton** [comment]
@danmilward 😙
