### ISSUE TITLE
PayPal Express Error Code: 10525

### ISSUE THREAD

**Issue by ablears** [wp-e-commerce/WP-e-Commerce#695]
I'm using 3.8.12.1 with DPS/Payment Express and PayPal Express Checkout 2.0 for a South African store (currency set to RAND, in WPSC's PayPal settings this is set to convert to USD). PE works fine. With PayPal Express I am getting this error:

SetExpressCheckout API call failed. 
Detailed Error Message: This transaction cannot be processed. The amount to be charged is zero.
Short Error Message: Invalid Data
Error Code: 10525
Error Severity Code: Error

In paypal-express.merchant.php I see this in the submit function:
$paymentAmount = $this->cart_data['total_price'];
This outputs the correct amount (eg 250)

$this->convert( $paymentAmount )
outputs 0

So the original amount is correct but converting it sets it to zero.

**Comment by tonyzeoli** [comment]
Hi,

I know this issue was closed sometime ago, but I'm working on a website: dvjvision.com, which uses wpecommerce and the gold cart plugin for a digital download store.

I'm working in staging to try to resolve: dvjvision.staging.wpengine.com

The client was having issues with PayPal not being able to process the request because the amount returned to be charged was zero. I cleared out the shopping cart, added my own credentials from PayPal and set the IPN to on with the return URL.

I then went to checkout with the new credentials and I'm getting a 502 error:

The www.paypal.com page isn’t working

www.paypal.com is currently unable to handle this request.
HTTP ERROR 502

Can someone help?
